config/routes.rb
TUCCSA2::Application.routes.draw do

  #for error page
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  resources :cs_applications
  resources :ratings
  resources :recommendations
  resources :application_steps
  resources :institutions
  resources :mailing_addresses
  resources :dashboard

  devise_for :users
  root :to => 'cs_applications#index'

  get '/cs_application/send_invitation/:recommendation_id', :controller => 'cs_applications', :action => 'send_invitation', :as => :send_invitation
  get '/cs_application/review/:id', :controller => 'cs_applications', :action => 'review', :as => :review_application
  get '/ratings/verify_password/:id', :controller=>'ratings', :action=>'verify_password', :as => :verify_password
  get '/ratings/submit_password/:id', :controller=>'ratings', :action=>'submit_password', :as => :submit_password
  get '/cs_application/download_package/:id', :controller=>'cs_applications', :action=>'download_package', :as => :download_package
  get '/cs_application/mark_as_reviewed/:id', :controller=>'cs_applications', :action=>'mark_as_reviewed', :as => :mark_as_reviewed
  get '/cs_application/mark_as_denied/:id', :controller=>'cs_applications', :action=>'mark_as_denied', :as => :mark_as_denied
  get '/cs_application/mark_as_approved/:id', :controller=>'cs_applications', :action=>'mark_as_approved', :as => :mark_as_approved
  get '/cs_application/submit_application/:id', :controller=>'cs_applications', :action=>'submit_application', :as => :submit_application
  get '/cs_application/edit/:id', :controller=>'cs_applications', :action=>'edit', :as => :edit_application
  get '/cs_application/remove_transcript/:cs_application_id', :controller=>'cs_applications', :action=>'remove_transcript', :as=> :remove_transcript
  get '/cs_application/remove_purpose/:cs_application_id', :controller=>'cs_applications', :action=>'remove_purpose', :as=> :remove_purpose


  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :status,:commitment, :independent, :intellect, :leadership, :maturity, :reliability, :skill, :timeliness, :notes, :verbal, :written

  belongs_to :recommendation

  STATUS_COMPLETED = "COMPLETED"
end

app/controllers/ratings_controller.rb
class RatingsController < InheritedResources::Base
  load_and_authorize_resource
  skip_authorize_resource :only => [:update, :edit, :destroy]

  def update
    @rating = Rating.find(params[:id])
    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        
        format.html { render action: "show", notice: 'Thank you, your ratings have been submitted. You can either edit your ratings or close this browser.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", notice: 'Something went wrong' }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @rating = Rating.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # verfify password before accessing the rating page
  def verify_password
    @rating = Rating.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # check if the password is matched
  def submit_password
    @password = params[:password]
    if @password == Rating.find_by_id(params[:rating_id]).password
      redirect_to "/ratings/#{params[:id]}/edit", notice: 'Verification Complete. Thank you.'
    else
      redirect_to verify_password_path(params[:id]), notice: 'Password verification failed, please try again.'
    end
  end
  
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def get_rating(number)
    rating = "Undefined"
    case number
    when 1
      rating = "Horrible"
    when 2
      rating = "Poor"
    when 3
      rating = "Mediocre"
    when 4
      rating = "Good"
    when 5
      rating = "Excellent"
    else
      rating = "Not Provided"
    end
  end
end

app/views/ratings/_form.html.erb
<h5>Please fill this form as accurately as possible. </h5>

<h5>5 is the highest score where as 1 is the lowest.</h5>
<br />
<strong>Student Details </strong>
<br /> <br />
Student's Name: <%= @rating.recommendation.cs_application.first_name%>&nbsp;<%= @rating.recommendation.cs_application.middle_name unless @rating.recommendation.cs_application.middle_name.nil? %>&nbsp;<%= @rating.recommendation.cs_application.last_name%><br />
Student's TU ID: <%= @rating.recommendation.cs_application.towson_id_number%><br />
Student's email: <%= @rating.recommendation.cs_application.email%><br />
<br /><br />
<strong>Recommender's Details (as provided by the student)</strong>
<br /><br />
Name: <%= @rating.recommendation.name%> <br />
Title: <%=@rating.recommendation.title%> <br />
Contact: <%=@rating.recommendation.email%>
<br />
<hr>
<%= form_for @rating, :html => { :class => 'form-horizontal rating-form' } do |f| %>
  <br />
  <%= f.hidden_field :recommendation_id %>
  <%= f.hidden_field :status, :value=>Rating::STATUS_COMPLETED %>
  <div class="control-group">
    <%= f.label :intellect, :class => 'control-label' %>
    <div class="controls inline">
      <%= f.select :intellect,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :leadership, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :leadership,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :written, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :written,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :verbal, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :verbal,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reliability, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :reliability,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timeliness, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :timeliness,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :maturity, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :maturity,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :skill, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :skill,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :commitment, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :commitment,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :independent, :class => 'control-label' %>
    <div class="controls inline">
    	<%= f.select :independent,[['Horrible',1],['Poor',2],['Mediocre',3],['Good',4],['Excellent',5]], :class => 'number_field' %>
    </div>
  </div>
    <br /> <br />
  <div class="control-group">
    <%= f.label :additional_notes, :class => 'control-label' %>
    <br /> <br />
    <div class="controls">
    	<%= f.text_area :notes %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Submit My Ratings', :class => 'btn btn-primary' %>

  </div>
<% end %>

app/views/ratings/edit.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h2>Please complete the recommendation form</h2>
</div>
<%= render :partial => 'form' %>

app/views/ratings/index.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:recommendation_id) %></th>
      <th><%= model_class.human_attribute_name(:intellect) %></th>
      <th><%= model_class.human_attribute_name(:leadership) %></th>
      <th><%= model_class.human_attribute_name(:written) %></th>
      <th><%= model_class.human_attribute_name(:verbal) %></th>
      <th><%= model_class.human_attribute_name(:reliability) %></th>
      <th><%= model_class.human_attribute_name(:timeliness) %></th>
      <th><%= model_class.human_attribute_name(:maturity) %></th>
      <th><%= model_class.human_attribute_name(:skill) %></th>
      <th><%= model_class.human_attribute_name(:commitment) %></th>
      <th><%= model_class.human_attribute_name(:independent) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= link_to rating.id, rating_path(rating) %></td>
        <td><%= rating.recommendation_id %></td>
        <td><%= rating.intellect %></td>
        <td><%= rating.leadership %></td>
        <td><%= rating.written %></td>
        <td><%= rating.verbal %></td>
        <td><%= rating.reliability %></td>
        <td><%= rating.timeliness %></td>
        <td><%= rating.maturity %></td>
        <td><%= rating.skill %></td>
        <td><%= rating.commitment %></td>
        <td><%= rating.independent %></td>
        <td><%=l rating.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rating_path(rating), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rating_path(rating),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rating_path,
            :class => 'btn btn-primary' %>

app/views/ratings/new.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ratings/show.html.erb
<%- model_class = Rating -%>
<div class="page-header">
  <h1>Your Ratings Summary</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:intellect) %>:</strong></dt>
  <dd><%= get_rating(@rating.intellect) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:leadership) %>:</strong></dt>
  <dd><%= get_rating(@rating.leadership) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:written) %>:</strong></dt>
  <dd><%= get_rating(@rating.written) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:verbal) %>:</strong></dt>
  <dd><%= get_rating(@rating.verbal) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reliability) %>:</strong></dt>
  <dd><%= get_rating(@rating.reliability) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timeliness) %>:</strong></dt>
  <dd><%= get_rating(@rating.timeliness) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:maturity) %>:</strong></dt>
  <dd><%= get_rating(@rating.maturity) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skill) %>:</strong></dt>
  <dd><%= get_rating(@rating.skill) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:commitment) %>:</strong></dt>
  <dd><%= get_rating(@rating.commitment) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:independent) %>:</strong></dt>
  <dd><%= get_rating(@rating.independent) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @rating.notes %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rating_path(@rating), :class => 'btn btn-mini btn-info' %>
  <%= link_to t('.close'),root_url, :id => 'close-window', :class => 'btn btn-warning' %>
</div>
<script>
	$(document).ready(function() {
		$("#close-window").click(function(event) {
			window.opener=self;
			window.close();
			event.preventDefault();
		});
	});
</script>

app/views/ratings/verify_password.html.erb
<br />
<h4>Thank you for taking time to provide your recommendations to the applicant. Your input will help us decide whether to accept this application or
to discard it. </h4>

<strong>Recommender's Details (as provided by the student)</strong><br />
Name: <%= @rating.recommendation.name%> <br />
Title: <%=@rating.recommendation.title%> <br />
Contact: <%=@rating.recommendation.email%>
<br /><hr />

<br />
Please verify the password provided to you in your invitation email to continue.
<br />
<%= form_tag submit_password_path(@rating.id), :method => 'get', :id=> @rating.id do %>
	Password: <%= password_field_tag :password%>
	<%= hidden_field_tag :rating_id, @rating.id %>
	<%= submit_tag "Verify"%>
<% end%>