config/routes.rb
TUCCSA2::Application.routes.draw do

  #for error page
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  resources :cs_applications
  resources :ratings
  resources :recommendations
  resources :application_steps
  resources :institutions
  resources :mailing_addresses
  resources :dashboard

  devise_for :users
  root :to => 'cs_applications#index'

  get '/cs_application/send_invitation/:recommendation_id', :controller => 'cs_applications', :action => 'send_invitation', :as => :send_invitation
  get '/cs_application/review/:id', :controller => 'cs_applications', :action => 'review', :as => :review_application
  get '/ratings/verify_password/:id', :controller=>'ratings', :action=>'verify_password', :as => :verify_password
  get '/ratings/submit_password/:id', :controller=>'ratings', :action=>'submit_password', :as => :submit_password
  get '/cs_application/download_package/:id', :controller=>'cs_applications', :action=>'download_package', :as => :download_package
  get '/cs_application/mark_as_reviewed/:id', :controller=>'cs_applications', :action=>'mark_as_reviewed', :as => :mark_as_reviewed
  get '/cs_application/mark_as_denied/:id', :controller=>'cs_applications', :action=>'mark_as_denied', :as => :mark_as_denied
  get '/cs_application/mark_as_approved/:id', :controller=>'cs_applications', :action=>'mark_as_approved', :as => :mark_as_approved
  get '/cs_application/submit_application/:id', :controller=>'cs_applications', :action=>'submit_application', :as => :submit_application
  get '/cs_application/edit/:id', :controller=>'cs_applications', :action=>'edit', :as => :edit_application
  get '/cs_application/remove_transcript/:cs_application_id', :controller=>'cs_applications', :action=>'remove_transcript', :as=> :remove_transcript
  get '/cs_application/remove_purpose/:cs_application_id', :controller=>'cs_applications', :action=>'remove_purpose', :as=> :remove_purpose


  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/controllers/application_steps_controller.rb
class ApplicationStepsController < ApplicationController
  before_filter :authenticate_user!

  # included the wizard gem for step form and get steps from mailing address model
  include Wicked::Wizard
  steps *MailingAddress.form_steps

  # display the next page in the step form
  def show
    @cs_application = current_user.cs_application

    case step

      when "mailing_address"
        if @cs_application.mailing_address.present?
          @contact = @cs_application.mailing_address
          @contact.name = @cs_application.first_name + " " + @cs_application.last_name
          puts 'found record......'
        else
          puts 'new record......'
          @contact = @cs_application.build_mailing_address
          @contact.name = @cs_application.first_name + " " + @cs_application.last_name
        end

      when "educational"
        if !params[:Add].nil?

          @institution = @cs_application.institutions.build

          @institution_all = @cs_application.institutions
          puts '-------------------------------add-----------------'
        else
          if @cs_application.institutions.present?
            @institution_all = @cs_application.institutions
            @institution = @cs_application.institutions.last
            puts '-------------------------------if-----------------'
          else
            @institution_all = @cs_application.institutions
            @institution = @cs_application.institutions.build
            puts '-------------------------------else-----------------'
          end
        end

      when "purpose_statement"
        if @cs_application.purpose_statement.present?
        @purpose_statement = @cs_application.purpose_statement
        else
        @purpose_statement = @cs_application.build_purpose_statement
        end


      when "transcripts"
        @transcript = @cs_application.transcripts.build
        @transcript_all = @cs_application.transcripts
      #else


      when "send_recommendations"
        if @cs_application.recommendations.size==1
          @recommendation1 = @cs_application.recommendations.first
          @recommendation2 = @cs_application.recommendations.build
        elsif @cs_application.recommendations.size==2
          @recommendation1 = @cs_application.recommendations.first
          @recommendation2 = @cs_application.recommendations.second
        else
          @recommendation1 = @cs_application.recommendations.build
          @recommendation2 = @cs_application.recommendations.build
        end

    end

    render_wizard

  end

  # update the form on submission
  def update
    @cs_application = current_user.cs_application
    case step
      
    when "mailing_address"
      if @cs_application.mailing_address.present?
        @contact = @cs_application.mailing_address
        @contact.update(form_params(step))
      else
        @contact = MailingAddress.new(form_params(step))
      end
      @contact.cs_application_id = @cs_application.id
      @contact.save


      update_progress(15, 30)
      render_wizard @contact
      
    when "educational"
      if params[:commit]== "Add"
        @institution = Institution.new
        @institution.cs_application_id = @cs_application.id
        @institution.update(form_params(step))
        @institution.save
        puts '-------------------------------add-----------------'
        render_wizard
      else
        if @cs_application.institutions.present?
          @institution = @cs_application.institutions.last
          @institution.update(form_params(step))
          puts '-------------------------------if-----------------'
        else
          @institution = Institution.new(form_params(step))
        end
          @institution.cs_application_id = @cs_application.id
          @institution.save
          update_progress(15, 45)
          redirect_to_review(@institution)

      end

      when "purpose_statement"
        @purpose_statement = @cs_application.purpose_statement

        if params[:commit]== "Upload"
          check = params[:purpose_statement][:purpose].nil? rescue true
          if check
            puts "check"
            render_wizard
          elsif @cs_application.purpose_statement.present?
            puts "exist"
            @purpose_statement.update(form_params(step))
            render_wizard
          else
            puts "new"
            @purpose_statement = PurposeStatement.new(:purpose => params[:purpose_statement][:purpose])
            @purpose_statement.cs_application_id = @cs_application.id
            @purpose_statement.save
            render_wizard
          end
        else
          if !@cs_application.purpose_statement.present?
            @purpose_statement = PurposeStatement.new
          end
          update_progress(15, 60)
          #render_wizard @purpose_statement
          redirect_to_review(@purpose_statement)

        end

      when "transcripts"
      if params[:commit]== "Upload"
          check = params[:transcript][:document].nil? rescue true
          if check
            render_wizard
          else
          @transcript = Transcript.new(:document => params[:transcript][:document])
          @transcript.cs_application_id = @cs_application.id
          @transcript.save
          render_wizard
          end
      else
        if @cs_application.transcripts.present?
          @transcript = @cs_application.transcripts.last
          @transcript.update(form_params(step))
        else
          @transcript = Transcript.new
        end
        update_progress(15, 75)
       # render_wizard @transcript
        redirect_to_review(@transcript)

      end

      when "send_recommendations"
      if @cs_application.recommendations.size==1
        @recommendation1 = @cs_application.recommendations.first
        @recommendation1.update(form_params(step))
        @recommendation1.cs_application_id = @cs_application.id
        @recommendation1.save
        @recommendation2 = Recommendation.new(recommendation2_params)
        @recommendation2.cs_application_id = @cs_application.id
        @recommendation2.save

      elsif @cs_application.recommendations.size==2
        @recommendation1 = @cs_application.recommendations.first
        @recommendation1.update(form_params(step))
        @recommendation1.cs_application_id = @cs_application.id
        @recommendation1.save

        @recommendation2 = @cs_application.recommendations.second
        @recommendation2.update(recommendation2_params)
        @recommendation2.cs_application_id = @cs_application.id
        @recommendation2.save
      else
        @recommendation1 = Recommendation.new(form_params(step))
        @recommendation1.cs_application_id = @cs_application.id
        @recommendation1.save
        @recommendation2 = Recommendation.new(recommendation2_params)
        @recommendation2.cs_application_id = @cs_application.id
        @recommendation2.save
      end
        update_progress(15, 90)

      if @recommendation1.save && @recommendation2.save
        redirect_to "/application_steps/send_email/"
      else
        render_wizard
      end

      when "send_email"
        render_wizard @cs_application
    end

  rescue ActiveRecord::RecordNotFound

  end

  # update the progress bar
  private
  def update_progress(percent_update, percent_completed)

    if @cs_application.progress!=100 && @cs_application.progress < percent_completed
      @cs_application.progress = @cs_application.progress + percent_update
    elsif @cs_application.progress == 100
      @cs_application.progress =100
    else
      @cs_application.save
    end

    @cs_application.save
  end

  # redirect to the review if the progress bar is 100%,
  # if not render the next page in the step form
  private
  def redirect_to_review(object)
    if @cs_application.progress<100
      render_wizard object
    else
      if object.save
        redirect_to "/cs_application/review/#{@cs_application.id}"
      else
        render_wizard
      end
    end
  end

  # Strong parameters for forms to permit the attributes on update.
  private
  def form_params(step)
    permitted_attributes = case step
                             when "mailing_address"
                               [:city, :address_line1, :address_line2, :name, :state_id, :zip]
                             when "educational"
                               [:attended_from, :attended_to, :city, :degree, :institution, :state_id]
                             when "send_recommendations"
                               [:email, :name, :status, :time_known_from, :time_known_to, :title]
                             when "transcript"
                               [:document]
                             when "purpose_statement"
                               [:purpose]
                           end

    if step == "mailing_address"
      params.require(:mailing_address).permit(permitted_attributes).merge(form_step: step)
    elsif step == "educational"
      params.require(:institution).permit(permitted_attributes).merge(form_step: step)
    elsif step == "send_recommendations"
      params.require(:recommendation1).permit(permitted_attributes).merge(form_step: step)
    elsif step == "transcript"
      params.require(:transcript).permit(permitted_attributes).merge(form_step: step)
    elsif step == "purpose_statement"
      params.require(:purpose_statement).permit(permitted_attributes).merge(form_step: step)
    end
  end

  def recommendation2_params
    params.require(:recommendation2).permit(:email, :name, :status, :time_known_from, :time_known_to, :title).merge(form_step: step)
  end

end

app/helpers/application_steps_helper.rb
module ApplicationStepsHelper
end

app/views/application_steps/complete.html.erb
<h2>Review and submit your application</h2>
<h3>We will notify via email when your application is accepted.</h3>

<!-- <edit_cs_application_path(@cs_application)> -->

<h3><%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %> <%= link_to 'Review Application' ,review_application_path(@cs_application), :class=>'btn btn-info'%>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cs_application_path(@cs_application),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>
  <%#= link_to 'Send' ,root_url, :class=>'btn'%>
</h3>

app/views/application_steps/educational.html.erb
<%= form_for @institution, method: :put, url: wizard_path, :html => { :class => 'form-horizontal' }  do |institute|  %>

	<!--<div class="page-header">
  		<h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
	</div>-->
    <div class="page-header">
	    <h2>Provide Your Educational Information</h2>
	</div>
	<%#= fields_for :institution do |institute|%>
		<div class="control-group">
			<%= institute.label :institution, :class => 'control-label' %>
			<div class="controls">
				<%= institute.text_field :institution, :class => 'text_field' %>
                <% unless !@institution.errors.has_key?(:institution)%>
                  <span class="help-inline"><%= @institution.errors[:institution].join(", ") %></span>
                <%end%>
			</div>
		</div>
		<div class="control-group">
			<%= institute.label :city, :class => 'control-label' %>
			<div class="controls">
              <%= institute.text_field :city, :class => 'text_field' %>
              <% unless !@institution.errors.has_key?(:city)%>
                  <span class="help-inline"><%= @institution.errors[:city].join(", ") %></span>
              <%end%>
			</div>
		</div>
		<div class="control-group">
			<%= institute.label :state_id, :class => 'control-label' %>
			<div class="controls">
              <%=institute.collection_select(:state_id, State.all, :id, :name, :selected => @institution.state_id)%>
              <% unless !@institution.errors.has_key?(:state_id)%>
                  <span class="help-inline"><%= @institution.errors[:state_id][1] %></span>
              <%end%>
            </div>
		</div>
        <br />
		<div class="control-group">
			<%= institute.label :attended_from, :class => 'control-label' %>
			<div class="controls">
				<%= institute.text_field :attended_from, :class => 'datepicker' %>
              <% unless !@institution.errors.has_key?(:attended_from)%>
                  <span class="help-inline"><%= @institution.errors[:attended_from].join(", ") %></span>
              <%end%>
			</div>
		</div>
		<div class="control-group">
			<%= institute.label :attended_to, :class => 'control-label' %>
			<div class="controls">
				<%= institute.text_field :attended_to, :class => 'datepicker' %>
              <% unless !@institution.errors.has_key?(:attended_to)%>
                  <span class="help-inline"><%= @institution.errors[:attended_to].join(", ") %></span>
              <%end%>
			</div>
		</div>
		<div class="control-group">
			<%= institute.label :degree, :class => 'control-label' %>
			<div class="controls">
				<%= institute.text_field :degree, :class => 'text_field' %>
              <% unless !@institution.errors.has_key?(:degree)%>
                  <span class="help-inline"><%= @institution.errors[:degree].join(", ") %></span>
              <%end%>
			</div>
		</div>

	<%# end%>

	<div class="form-actions">
		
		<%= institute.submit "Save", :value => 'Add' ,:class => 'btn btn-inverse' %>

        <% if @cs_application.progress == 100 %>
		    <%= institute.submit "Update Institution", :class => 'btn btn-primary' %>
        <%else%>
          <%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %>
          <%= institute.submit "Next", :class => 'btn btn-primary' %>
      <%end%>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-warning' %>
	</div>
<% end%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Institution</th>
      <th>City</th>
      <th>State</th>
      <th>Dates Attended</th>
      <th>Degree</th>
    </tr>
  </thead>
  <tbody>
	  <h3>Saved Institutions</h3>
	  <% current_user.cs_application.institutions.each do |institution|%>
	  <tr>
        <td><%= institution.institution %></td>
        <td><%= institution.city %></td>
        <td><%= State.find_by_id(institution.state_id).name unless institution.state_id.nil? %></td>
        <td><%= institution.attended_from %> - <%= institution.attended_to %></td>
        <td><%= institution.degree %></td>
        <td>
        	<% if !institution.id.nil? %>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_institution_path(institution), :class => 'btn btn-info' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      institution_path(institution),
	                      :method => :delete,
	                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                      :class => 'btn btn-mini btn-danger' %>
            <%end%>
        </td>
      </tr>
      <% end%>
	</tbody>
</table>
<br /><br />



<script>
	$('.datepicker').datepicker()
</script>

app/views/application_steps/mailing_address.html.erb
<%= form_for @contact, method: :put, url: wizard_path do |contact| %>

    <!--<div class="page-header">
      <h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
    </div>-->
    <div class="page-header">
     <h2>Provide Your Mailing Information</h2>
    </div>
    <fieldset>
      <div class="control-group">
        <%= contact.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= contact.text_field :name, :class => 'text_field' %>
          <% unless !@contact.errors.has_key?(:name)%>
              <span class="help-inline"><%= @contact.errors[:name].join(", ") %></span>
          <%end%>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :address_line1, :class => 'control-label' %>
        <div class="controls">
          <%= contact.text_field :address_line1, :class => 'text_field' %>
          <% unless !@contact.errors.has_key?(:address_line1)%>
              <span class="help-inline"><%= @contact.errors[:address_line1].join(", ") %></span>
          <%end%>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :address_line2, :class => 'control-label' %>
        <div class="controls">
          <%= contact.text_field :address_line2, :class => 'text_field' %>
          <% unless !@contact.errors.has_key?(:address_line2)%>
              <span class="help-inline"><%= @contact.errors[:address_line2].join(", ") %></span>
          <%end%>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :city, :class => 'control-label' %>
        <div class="controls">
          <%= contact.text_field :city, :class => 'text_field' %>
          <% unless !@contact.errors.has_key?(:city)%>
              <span class="help-inline"><%= @contact.errors[:city].join(", ") %></span>
          <%end%>
        </div>
      </div>
      <div class="control-group">
        <%= contact.label :state_id, :class => 'control-label' %>
        <div class="controls">
          <%=contact.collection_select(:state_id, State.all, :id, :name, :selected => @contact.state_id) %>
          <% unless !@contact.errors.has_key?(:state_id)%>
              <span class="help-inline"><%= @contact.errors[:state_id][1] %></span>
          <%end%>
        </div>
      </div>
      <br />
      <div class="control-group">
        <%= contact.label :zip, :class => 'control-label' %>
        <div class="controls">
          <%= contact.number_field :zip, :class => 'number_field' %>
          <% unless !@contact.errors.has_key?(:zip)%>
              <span class="help-inline"><%= @contact.errors[:zip].join(", ") %></span>
          <%end%>
        </div>
      </div>

      <div class="form-actions">
        <%= link_to t('.back'), edit_cs_application_path(@cs_application), :class => 'btn btn-default' %>
        <%= contact.submit "Next", :class => 'btn' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-warning' %>
      </div>

    </fieldset>
<% end %>

app/views/application_steps/purpose_statement.html.erb
<%= form_for @purpose_statement, method: :put, url: wizard_path, :html => { :multipart => true, :class => 'form-horizontal' }  do |f|  %>

    <!--<div class="page-header">
      <h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
	</div>-->
    <div class="page-header">
	    <h2>Attach your Purpose Statement</h2>
    </div>
	<div class="control-group">
	   <%#= f.label :purpose_statement, :class => 'control-label' %>
      <div class="controls">
	       <p class ="guide">Attach a PDF file (.pdf) containing a brief statement of purpose describing your goals
	       and motivations to pursue a career in Information Assurance and Computer Security (Max 2 pages)</p>
	       <br />
           <%= f.file_field :purpose %>
            <% unless !@purpose_statement.errors.has_key?(:purpose)%>
                <span class="help-inline"><%= @purpose_statement.errors[:purpose].join(", ") %></span>
            <%end%>

            <%= f.submit "Save", :value => 'Upload' ,:class => 'btn', disabled: true %>
            <br /><br />
            <strong>Uploaded File:</strong>
            <br /><br />
              <% if !@purpose_statement.id.nil?%>
                File received: <%= link_to @purpose_statement.purpose_file_name, @purpose_statement.purpose.url, :target => '_blank'%>
                <%=link_to t('.Remove'), remove_purpose_path(@purpose_statement.id), :confirm => 'You are about to remove your uploaded file. Continue?', :class=>'btn btn-danger custom-btn'%>
                <br />
              <% end%>
	    </div>
	</div>
	<hr />

  	<div class="form-actions">
      <% if @cs_application.progress == 100 %>
          <%= f.submit "Update Purpose Statement", :class => 'btn btn-primary' %>
      <%else%>
          <%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %>
          <%= f.submit "Next", :class => 'btn btn-primary' %>
      <%end %>
    	<%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-danger' %>
  	</div>
<% end%>

app/views/application_steps/send_email.html.erb
<%= form_for @cs_application, url: wizard_path, :html => { :class => 'form-horizontal' }  do |f|  %>

	<!--<div class="page-header">
  		<h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
	</div>-->
    <div class="page-header">
	<h2>Send Invitations for Recommendation</h2>
	</div>

	<h4>First Recommendation</h4>
	<% if !@cs_application.recommendations.first.nil? %>
		<% @recommendation1 = @cs_application.recommendations.first%>
		Name: <%= @recommendation1.name%> <br />
		Title: <%= @recommendation1.title%> <br />
		Email: <%= @recommendation1.email%> <br /><br />
		<% if !@recommendation1.email.nil? %>
			<% if @recommendation1.status=="SENT" || @recommendation1.status=="COMPLETED" %>
				<%= link_to "Resend Email", send_invitation_path(@recommendation1), :class => 'btn btn-success' %>
            <%else%>
				<%= link_to "Send Email", send_invitation_path(@recommendation1), :class => 'btn btn-success' %>
			<% end%>
		<% else %>
			<strong>*Please enter all information</strong>
		<% end %>
	<% else%>
		Information not available
	<% end%>
    <br /><br />
	<h4>Second Recommendation</h4>
	<% if !@cs_application.recommendations.second.nil? %>
		<% @recommendation2 = @cs_application.recommendations.second%>
		Name: <%= @recommendation2.name%> <br />
		Title: <%= @recommendation2.title%> <br />
		Email: <%= @recommendation2.email%> <br /><br />
		<% if !@recommendation2.email.nil?%>
			<% if @recommendation2.status=="SENT"  || @recommendation2.status=="COMPLETED" %>
				<%= link_to "Resend Email", send_invitation_path(@recommendation2), :class => 'btn btn-success' %>
            <%else%>
				<%= link_to "Send Email", send_invitation_path(@recommendation2), :class => 'btn btn-success' %>
            <% end%>
		<% else %>
			<strong>*Please enter all information</strong>
		<% end %>
	<% else%>
		Information not available
	<% end%>
	<hr />

	<div class="form-actions">
		<%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %>
		<%= f.submit "Next", :class => 'btn btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-warning' %>
	</div>

<% end%>

<br /><br />

app/views/application_steps/send_recommendations.html.erb
<%= form_for [@recommendation1,@recommendation2], method: :put, url: wizard_path, :html => { :class => 'form-horizontal' }  do |recommendation|  %>

    <!--<div class="page-header">
  		<h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
	</div>-->
    <div class="page-header">
	    <h2>Send Invitations for Recommendation</h2>
	</div>
	You need two letters of recommendations to complete this application. Fill the following form to send electronic
	recommendation invitations.
	<hr />

	<%= fields_for :recommendation1 do |recommendation1|%>
	<div class="control-group">
		<%= recommendation1.label :name, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation1.text_field :name, :class => 'text_field' %>
          <% unless !@recommendation1.errors.has_key?(:name)%>
              <span class="help-inline"><%= @recommendation1.errors[:name].join(", ") %></span>
          <%end%>
		</div>
	</div>
	<div class="control-group">
		<%= recommendation1.label :title, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation1.text_field :title, :class => 'text_field' %>
          <% unless !@recommendation1.errors.has_key?(:title)%>
              <span class="help-inline"><%= @recommendation1.errors[:title].join(", ") %></span>
          <%end%>
		</div>
	</div>
	<div class="control-group">
		<%= recommendation1.label :email, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation1.email_field :email, :class => 'email_field' %>
          <% unless !@recommendation1.errors.has_key?(:email)%>
              <span class="help-inline"><%= @recommendation1.errors[:email].join(", ") %></span>
          <%end%>
		</div>
	</div>

	<%end%>
	
	<hr />
	
	<%= fields_for :recommendation2 do |recommendation2|%>
	<div class="control-group">
		<%= recommendation2.label :name, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation2.text_field :name, :class => 'text_field' %>
          <% unless !@recommendation2.errors.has_key?(:name)%>
              <span class="help-inline"><%= @recommendation2.errors[:name].join(", ") %></span>
          <%end%>
		</div>
	</div>
	<div class="control-group">
		<%= recommendation2.label :title, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation2.text_field :title, :class => 'text_field' %>
          <% unless !@recommendation2.errors.has_key?(:title)%>
              <span class="help-inline"><%= @recommendation2.errors[:title].join(", ") %></span>
          <%end%>
		</div>
	</div>
	<div class="control-group">
		<%= recommendation2.label :email, :class => 'control-label' %>
		<div class="controls">
          <%= recommendation2.email_field :email, :class => 'email_field' %>
          <% unless !@recommendation2.errors.has_key?(:email)%>
              <span class="help-inline"><%= @recommendation2.errors[:email].join(", ") %></span>
          <%end%>
		</div>
	</div>

	<%end%>
	<hr />
	<div>
		You will get options to send invitations in next page.
	</div>
	<div class="form-actions">
		<%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %>
		<%= recommendation.submit "Next", :class => 'btn btn-success' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-warning' %>
	</div>

<% end%>
<br /><br />

app/views/application_steps/transcripts.html.erb
<%= form_for @transcript, method: :put, url: wizard_path, :html => { :multipart => true, :class => 'form-horizontal' }  do |f|  %>

    <!--<div class="page-header">
      <h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
    </div>-->
    <div class="page-header">
        <h2>Attach your Transcripts</h2>
    </div>
    <div class="control-group">
      <div class="controls">
        <p class ="guide">Click on 'Upload' after selecting your file to add another attachment. Attachments can be
        images of your scanned transcripts or PDF.</p>
        <br />
        <%= f.file_field :document %>
        <% unless !@transcript.errors.has_key?(:document)%>
            <span class="help-inline"><%= @transcript.errors[:document].join(", ") %></span>
        <%end%>

        <%= f.submit "Save", :value => 'Upload' ,:class => 'btn', disabled: true  %>

        <br /><br />
        <strong>Uploaded transcripts</strong>
        <br /><br />

        <table class="table">

          <% current_user.cs_application.transcripts.each do |transcript|%>
              <tr>
              <% if !transcript.id.nil? %>
                    <td><%=link_to transcript.document_file_name, transcript.document.url%></td>
                    <td><%=link_to t('.Remove'), remove_transcript_path(transcript.id), :confirm => 'You are about to remove your uploaded file. Continue?', :class=>'btn btn-danger custom-btn'%></td>
              <% end%>
              </tr>
          <% end%>

        </table>
      </div>
    </div>

    <div class="form-actions">
      <% if @cs_application.progress == 100 %>
          <%= f.submit "Update Transcript", :class => 'btn btn-primary' %>
      <%else%>
          <%= link_to t('.back'), previous_wizard_path, :class => 'btn btn-default' %>
          <%= f.submit "Next", :class => 'btn btn-primary' %>
      <%end %>

      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), cs_applications_path, :class => 'btn btn-warning' %>
    </div>

<% end%>