config/routes.rb
TUCCSA2::Application.routes.draw do

  #for error page
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  resources :cs_applications
  resources :ratings
  resources :recommendations
  resources :application_steps
  resources :institutions
  resources :mailing_addresses
  resources :dashboard

  devise_for :users
  root :to => 'cs_applications#index'

  get '/cs_application/send_invitation/:recommendation_id', :controller => 'cs_applications', :action => 'send_invitation', :as => :send_invitation
  get '/cs_application/review/:id', :controller => 'cs_applications', :action => 'review', :as => :review_application
  get '/ratings/verify_password/:id', :controller=>'ratings', :action=>'verify_password', :as => :verify_password
  get '/ratings/submit_password/:id', :controller=>'ratings', :action=>'submit_password', :as => :submit_password
  get '/cs_application/download_package/:id', :controller=>'cs_applications', :action=>'download_package', :as => :download_package
  get '/cs_application/mark_as_reviewed/:id', :controller=>'cs_applications', :action=>'mark_as_reviewed', :as => :mark_as_reviewed
  get '/cs_application/mark_as_denied/:id', :controller=>'cs_applications', :action=>'mark_as_denied', :as => :mark_as_denied
  get '/cs_application/mark_as_approved/:id', :controller=>'cs_applications', :action=>'mark_as_approved', :as => :mark_as_approved
  get '/cs_application/submit_application/:id', :controller=>'cs_applications', :action=>'submit_application', :as => :submit_application
  get '/cs_application/edit/:id', :controller=>'cs_applications', :action=>'edit', :as => :edit_application
  get '/cs_application/remove_transcript/:cs_application_id', :controller=>'cs_applications', :action=>'remove_transcript', :as=> :remove_transcript
  get '/cs_application/remove_purpose/:cs_application_id', :controller=>'cs_applications', :action=>'remove_purpose', :as=> :remove_purpose


  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/cs_application.rb
class CsApplication < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :middle_name, :towson_id_number,:is_citizen, :phone, :user_id

  belongs_to :user
  has_one :purpose_statement, :foreign_key => 'cs_application_id', :class_name => 'PurposeStatement', :dependent => :destroy
  has_many :recommendations, :dependent => :destroy
  has_one :mailing_address, :dependent => :destroy
  has_many :institutions, :dependent => :destroy
  has_many :transcripts, :dependent => :destroy
  accepts_nested_attributes_for :recommendations

  validates :first_name, :last_name, :towson_id_number, :phone, presence: true
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :towson_id_number, uniqueness: true, on: :create
  validates :first_name, :last_name,length: { in: 2..50 }
  validates :towson_id_number, length: { is: 7 }
  validates :phone, length: { is: 10 }
  validates :phone, numericality: { only_integer: true }
  #validates :email, email_format: true
  validates :is_citizen, :acceptance => {:accept => true, message: "This application requires applicants to be a US citizen." }

  STATUS_STARTED = "STARTED"
  STATUS_SUBMITTED = "SUBMITTED"
  STATUS_REVIEWED = "REVIEWED"
  STATUS_DENIED = "DENIED"
  STATUS_APPROVED = "APPROVED"

end

app/controllers/cs_applications_controller.rb
class CsApplicationsController < ApplicationController
  before_filter :authenticate_user!

  # load and authorize the actions once instead of defining on each action
  load_and_authorize_resource param_method: :my_sanitizer
  # skip authorization on the actions
  skip_authorize_resource :only => [:index, :new, :remove_purpose, :remove_transcript, :send_invitation, :submit_application]

  require 'rubygems'
  require 'zip'
  require "open-uri"

  @count = 0

  # GET /cs_applications
  # GET /cs_applications.json
 def index
   @cs_application = CsApplication.find_by_user_id(current_user.id)

   if current_user.is_admin?
       redirect_to "/admin/dashboard"
   else
     respond_to do |format|
     format.html # index.html.erb
     format.json { render json: @cs_applications }
     end
   end
  end

  # GET /cs_applications/1
  # GET /cs_applications/1.json
  def show
    @cs_application = CsApplication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cs_application }
    end
  end

  # GET /cs_applications/new
  # GET /cs_applications/new.json
  def new
    @cs_application = CsApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cs_application }
    end
  end

  # GET /cs_applications/1/edit
  def edit
    @cs_application = CsApplication.find(params[:id])
  end

  # POST /cs_applications
  # POST /cs_applications.json
  def create
   # @cs_application = CsApplication.new(params[:cs_application])
     @cs_application = CsApplication.new(my_sanitizer)
     @cs_application.email = current_user.email
     @cs_application.progress=15
     @cs_application.save
   
    respond_to do |format|
      if @cs_application.save
         @cs_application.status="STARTED"
         @cs_application.save
        format.html { redirect_to application_steps_path }
        format.json { render json: @cs_application, status: :created, location: @cs_application }
      else
        format.html { render action: "new" }
        format.json { render json: @cs_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cs_applications/1
  # PUT /cs_applications/1.json
  def update
   @cs_application = CsApplication.find(params[:id])

   if @cs_application.progress!=100
     if @cs_application.progress < 30
       @cs_application.progress=15
       @cs_application.save
     end
   end

    respond_to do |format|
      if @cs_application.update(my_sanitizer)
        if @cs_application.progress == 100
          format.html { redirect_to "/cs_application/review/#{@cs_application.id}", notice: 'Basic Information was successfully updated.' }
        else
          format.html { redirect_to application_steps_path}
          format.json { head :no_content }
        end
      else
          format.html { render action: "edit" }
          format.json { render json: @cs_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cs_applications/1
  # DELETE /cs_applications/1.json
  def destroy
    @cs_application = CsApplication.find(params[:id])
    @cs_application.destroy

    respond_to do |format|
      format.html { redirect_to cs_applications_url }
      format.json { head :no_content }
    end
  end


  # Deliver the recommendation link via email for rating
  def send_invitation
    recommendation = Recommendation.find_by_id(params[:recommendation_id])
    if recommendation.cs_application.progress !=100 && recommendation.cs_application.progress <100
      recommendation.cs_application.progress = recommendation.cs_application.progress + 5
      recommendation.cs_application.save
    end
    rating = Rating.new()
    recommendation.status = Recommendation::STATUS_SENT
    recommendation.save
    rating.recommendation_id = recommendation.id
    rating.password = generate_rating_code(8)
    rating.notes = "Enter you additional notes"
    rating.save
    link = "http://#{request.host}:#{request.port}/ratings/verify_password/#{rating.id}"
    UserMailer.send_invitation(recommendation, link, rating).deliver
    redirect_to '/application_steps/send_email/', :notice => 'Invitation Email Sent'
    #redirect_to verify_password_path(rating.id), :notice => 'Invitation Email Sent' 

  end

  # render the pdf
  def review
    @cs_application = CsApplication.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ApplicationReviewPdf.new(@cs_application, view_context)
         send_data pdf.render,
                               filename: "user_#{current_user.id}_#{@cs_application.id}.pdf",
                               type: "application/pdf",
                               disposition: "inline"
                                
        #Saving file
       # pdf = ApplicationReviewPdf.new(@cs_application, view_context)
       # save_path = Rails.root.join('pdfs',"filename.pdf")
        # File.open(save_path, 'wb') do |file|
          # file << pdf
       # end

      end
    end

  end

  # mark application status as reviewed
  def mark_as_reviewed
    cs_application = CsApplication.find_by_id(params[:id])
    if cs_application.progress<100
      redirect_to :back, :notice=>'You cannot mark this application as reviewed. The application is not yet submitted by the student.'
    else
      cs_application.status = CsApplication::STATUS_REVIEWED
      cs_application.save
      redirect_to :back #:notice=>'Application is now marked as reviewed. Student has been notified.'
    end
  end

  # mark application status as denied
  def mark_as_denied
    cs_application = CsApplication.find_by_id(params[:id])
    if cs_application.progress<100
      redirect_to :back, :notice=>'You cannot mark this application as denied. The application is not yet submitted by the student.'
    else
      cs_application.status = CsApplication::STATUS_DENIED
      cs_application.save
     # UserMailer.send_denied_message(cs_application).deliver
     redirect_to :back #:notice=>'Application is now marked as denied. Student has been notified.'
    end
  end

  # mark application status as approved
  def mark_as_approved
    cs_application = CsApplication.find_by_id(params[:id])
    if cs_application.progress!=100
      redirect_to :back, :notice=>'You cannot mark this application as approved. The application is not yet submitted by the student.'
    else
      cs_application.status = CsApplication::STATUS_APPROVED
      cs_application.save
     # UserMailer.send_approved_message(cs_application).deliver
     redirect_to :back #:notice=>'Application is now marked as approved. Student has been notified.'
    end
  end

  # download the attached documents
  def download_package
      cs_application = CsApplication.find_by_id(params[:id])
      file_name = "package.zip"
      transcripts_list = cs_application.transcripts
      purpose= cs_application.purpose_statement
      file_name  = "applicant_#{cs_application.user.id}_application_#{cs_application.id}"
      file_name  = "#{file_name}.zip"
      
      temp_file  = Tempfile.new("#{file_name}-#{cs_application.id}")
      Zip::OutputStream.open(temp_file.path) do |zos|
        zos.put_next_entry(purpose.purpose_file_name)
        zos.print IO.read(purpose.purpose.path)
        transcripts_list.each do |file|
          zos.put_next_entry(file.document_file_name)
          zos.print IO.read(file.document.path)
        end
      end
      
      send_file temp_file.path, :type => 'application/zip',
                                :disposition => 'attachment',
                                :filename => file_name
      temp_file.close
  end

  # generate rating code for the rating page
  def generate_rating_code(size = 8)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    (0...size).map{ charset.to_a[rand(charset.size)] }.join
  end

  # notifies the application has been submitted
  def submit_application
    application = CsApplication.find_by_id(params[:id])
    
    if application.progress<100
      redirect_to review_application_url, :notice => "You application is not complete yet and cannot be submitted at this time"
    else
      application.progress = 100
      application.status = CsApplication::STATUS_SUBMITTED
      application.save
      UserMailer.submit_application_applicant(application).deliver
      UserMailer.submit_application_admin(application).deliver
      redirect_to root_url, :notice => "Congratulations!! You have successfully submitted the application. We will get in touch with you."
    end
  end

  # remove the attached transcript
  def remove_transcript
    transcript = Transcript.find(params[:cs_application_id])
    transcript.destroy
    redirect_to :back, :notice => 'Transcript has been removed.'
  end

  # remove the attached purpose
  def remove_purpose
    purpose = PurposeStatement.find(params[:cs_application_id])
    #purpose = current_user.cs_application.purpose_statement
    purpose.destroy

    redirect_to :back, flash:{success: 'Purpose Statement has been removed.'}
  end

 # strong parameter for cs application to permit attributes on update
  private
  def my_sanitizer
    params.require(:cs_application).permit(:email, :first_name, :last_name, :middle_name, :towson_id_number,:is_citizen, :phone, :status, :progress, :user_id)
  end

end

app/helpers/cs_applications_helper.rb
module CsApplicationsHelper
end

app/views/cs_applications/_form.html.erb
<%= form_for @cs_application, :html => { :class => 'form-horizontal' } do |f| %>

    <div class="page-header">
        <h2>Provide Your Basic Information</h2>
    </div>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
      <% unless !@cs_application.errors.has_key?(:first_name)%>
        <span class="help-inline"><%= @cs_application.errors[:first_name].join(", ") %></span>
      <%end%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :middle_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :middle_name, :class => 'text_field' %>
      <% unless !@cs_application.errors.has_key?(:middle_name)%>
         <span class="help-inline"><%= @cs_application.errors[:middle_name].join(", ") %></span>
      <%end%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
      <% unless !@cs_application.errors.has_key?(:last_name)%>
         <span class="help-inline"><%= @cs_application.errors[:last_name].join(", ") %></span>
      <%end%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :towson_id_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :towson_id_number, :class => 'number_field' %>
      <% unless !@cs_application.errors.has_key?(:towson_id_number)%>
          <span class="help-inline"><%= @cs_application.errors[:towson_id_number].join(", ") %></span>
      <%end%>
    </div>
  </div>
  <!--<div class="control-group">
    <%#= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%#= f.text_field :email, :class => 'text_field', :value => current_user.email %>
      <%# unless !@cs_application.errors.has_key?(:email)%>
          <span class="help-inline"><%#= @cs_application.errors[:email].join(", ") %></span>
      <%#end%>
    </div>
  </div>-->
    <div class="control-group">
      <%= f.label :phone, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :phone, :class => 'number_field' %>
        <% unless !@cs_application.errors.has_key?(:phone)%>
            <span class="help-inline"><%= @cs_application.errors[:phone].join(", ") %></span>
        <%end%>
      </div>
    </div>
    <br />
    <div class="control-group">
      <div class="controls">
        <%= f.check_box :is_citizen, :class => 'number_field' %> Check if you are a US citizen.
        <% unless !@cs_application.errors.has_key?(:is_citizen)%>
            <span class="help-inline"><%= @cs_application.errors[:is_citizen].join(", ") %></span>
        <%end%>
      </div>
    </div>
	<%= f.hidden_field :user_id, :value => current_user.id%>
  <div class="form-actions">
    <% if @cs_application.progress == 100 %>
        <%= f.submit "Update Basic Information", :class => 'btn btn-primary', :onclick=> "validateCheckbox();" %>
    <%else%>
        <%= f.submit "Next", :class => 'btn btn-primary', :onclick=> "validateCheckbox();" %>
    <%end%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cs_applications_path, :class => 'btn btn-warning' %>
  </div>
<% end %>

app/views/cs_applications/edit.html.erb
<%- model_class = CsApplication -%>
<!--<div class="page-header">
 <h2><%#=t '.title', :default => t('Your Application', :default => "Your Application") %></h2>
</div>-->
<%= render :partial => 'form' %>

app/views/cs_applications/index.html.erb
<%- model_class = CsApplication -%>
<div class="page-header">
  <h2><%=t '.title', :default => "CyberCorps Scholarship Application" %></h2>
</div>

    <% if current_user %>
  		<% if !(current_user.cs_application.nil?)%>
  			<% if (@cs_application.status=="STARTED")%>
                <table class="table table-striped">
                <thead>
                    <tr>
                    <th><%= model_class.human_attribute_name(:id) %></th>
                    <th><%= model_class.human_attribute_name(:started_at) %></th>
                    </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @cs_application.id %></td>
                    <td><%=l @cs_application.created_at %></td>
                    <td>
                      <% if @cs_application.progress < 100 %>
                        <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_application_path(@cs_application), :class => 'btn btn-mini btn-info' %>
                       <%end %>
                        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              cs_application_path(@cs_application),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-mini btn-danger' %>
                        <%= link_to t('.review'),
                              review_application_path(@cs_application), :class => 'btn btn-mini btn-primary' %>
                    </td>
                  </tr>
                </tbody>
                </table>

	        <% else %>
                You have already submitted your application.
                <br />
                You are not allowed to edit your application after it has been submitted.
                <br /><br />
                View your submitted application: <%= link_to t('.view'), review_application_path(format: "pdf", id: CsApplication.find_by_user_id(current_user.id)), :target => '_blank', :class => 'btn btn-primary' %>
	        <% end%>
        <% end%>


        <% if (current_user.cs_application.nil?)%>
        <h3> You have not started your application yet.</h3>

        <%= link_to t('.new', :default => t("Start A New Application")),
                    new_cs_application_path,
                    :class => 'btn btn-primary' %>
        <% end%>

    <% end%>

app/views/cs_applications/new.html.erb
<%- model_class = CsApplication -%>
<!--<div class="page-header">
  <h2>Your Application</h2>
</div>-->
<%= render :partial => 'form' %>

app/views/cs_applications/review.html.erb
<br />
<h2>Review Your Application</h2>
<br />
<div id="wrap">
  <br />
	<div class="title">
		<h4>Basic Information (<%= link_to "Edit", edit_cs_application_path(@cs_application) %>)</h4>
	</div>
	<div class="left_col">
		First Name
	</div>
	<div class="right_col">
		<%= !@cs_application.first_name.blank? ? @cs_application.first_name : 'Not Provided' %>
	</div>
	<div class="left_col">
		Middle Name
	</div>
	<div class="right_col">
		<%= !@cs_application.middle_name.blank? ? @cs_application.middle_name : 'Not Provided' %>
	</div>
	<div class="left_col">
		Last Name
	</div>
	<div class="right_col">
		<%= !@cs_application.last_name.blank? ? @cs_application.last_name : 'Not Provided' %>
	</div>
		<div class="left_col">
		TU ID
	</div>
	<div class="right_col">
		<%= !@cs_application.towson_id_number.blank? ? @cs_application.towson_id_number : 'Not Provided' %>
	</div>
	<div class="left_col">
		Contact Email
	</div>
	<div class="right_col">
		<%= !@cs_application.email.blank? ? @cs_application.email : 'Not Provided' %>
	</div>
		<div class="left_col">
		US Citizen?
	</div>
	<div class="right_col">
      <% if @cs_application.is_citizen == true ? citizen = "Yes" : citizen ="No" %>
           <%= !@cs_application.is_citizen.blank? ? citizen : 'Not Provided' %>
	    <%end%>
    </div>
        <div class="left_col">
        Telephone
    </div>
    <div class="right_col">
    <%= !@cs_application.phone.blank? ? @cs_application.phone : 'Not Provided' %>
    </div>

    <br />
	<div class="title">
		<h4>Contact Information (<%= link_to "Edit", edit_mailing_address_path(@cs_application.mailing_address)%>)</h4>
	</div>
    <div class="left_col">
		Name
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.name.blank? ? @cs_application.mailing_address.name : 'Not Provided' %>
	</div>
	<div class="left_col">
		Address Line1
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.address_line1.blank? ? @cs_application.mailing_address.address_line1 : 'Not Provided' %>
	</div>
	<div class="left_col">
		Address Line2
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.address_line2.blank? ? @cs_application.mailing_address.address_line2 : 'Not Provided' %>
	</div>
		<div class="left_col">
		City
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.city.blank? ? @cs_application.mailing_address.city : 'Not Provided' %>
	</div>
	<div class="left_col">
		State
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.state_id.blank? ? @cs_application.mailing_address.state.name : 'Not Provided' %>
	</div>
	<div class="left_col">
		Zip
	</div>
	<div class="right_col">
		<%= !@cs_application.mailing_address.zip.blank? ? @cs_application.mailing_address.zip : 'Not Provided' %>
	</div>

    <br />
	<% @cs_application.institutions.each do |institution|%>
      <div class="title">
        <h4>Educational Information (<%= link_to "Edit", "/application_steps/educational" %>)</h4>
      </div>
		<div class="left_col">
			Institution
		</div>
		<div class="right_col">
			<%= !institution.institution.blank? ? institution.institution : 'Not Provided' %>
		</div>
		<div class="left_col">
			City
		</div>
		<div class="right_col">
			<%= !institution.city.blank? ? institution.city : 'Not Provided' %>
		</div>
		<div class="left_col">
			Attended From
		</div>
		<div class="right_col">
			<%= !institution.attended_from.blank? ? institution.attended_from : 'Not Provided' %>
		</div>
		<div class="left_col">
			Attended To
		</div>
		<div class="right_col">
			<%= !institution.attended_to.blank? ? institution.attended_to : 'Not Provided' %>
		</div>
		<div class="left_col">
			Degree
		</div>
		<div class="right_col">
			<%= !institution.degree.blank? ? institution.degree : 'Not Provided' %>
		</div>
	<% end%>
    <br />
	<div class="title">
		<h4>Purpose (<%= link_to "Edit", "/application_steps/purpose_statement" %>)</h4>
	</div>
	<div class="left_col">
		Purpose Statement
	</div>
	<div class="right_col">
        <% @purpose_statement = @cs_application.purpose_statement%>
		<%= !@purpose_statement.purpose.nil? ? (link_to @purpose_statement.purpose_file_name, @purpose_statement.purpose.url) : "Not Provided"%>
	</div>

    <br />
    <div class="title">
        <h4>Transcript (<%= link_to "Edit", "/application_steps/transcripts" %>)</h4>
     </div>
	<div class="left_col">
		Transcript(s)
	</div>
	<div class="right_col">
		<% @transcript_all = @cs_application.transcripts%>
      <ul>
		<% @transcript_all.each do |transcript|%>
			<li><%=link_to transcript.document_file_name, transcript.document.url%></li>
		<% end%>
      </ul>
	</div>

	<div class="title">
		<h4>Recommendations (<%= link_to "Edit", "/application_steps/send_recommendations" %>)</h4>
	</div>
	<% if !@cs_application.recommendations.first.nil? %>
		<% @recommendation1 = @cs_application.recommendations.first%>
		<div class="left_col">
			Name: <%= @recommendation1.name%>
		</div>
		<div class="right_col">
			Status:
			<% if @recommendation1.status=="SENT"%>
				Invitation Sent
			<% else%>
				Not Sent (<%= link_to "Send an email to complete an application", "/application_steps/send_email" %>)

			<% end%>
		</div>
	<% else %>
		<div class="left_col">
			Name: Not Provided
		</div>
		<div class="right_col">
			Status: -
		</div>
	<% end%>
	
	<% if !@cs_application.recommendations.second.nil? %>
		<% @recommendation2 = @cs_application.recommendations.second%>
		<div class="left_col">
			Name: <%= @recommendation2.name%>
		</div>
		<div class="right_col">
			Status:
			<% if @recommendation2.status=="SENT"%>
				Invitation Sent
			<% else%>
				Not Sent (<%= link_to "Send an email to complete an application", "/application_steps/send_email" %>)
			<% end%>
		</div>
	<% else %>
		<div class="left_col">
			Name: Not Provided
		</div>
		<div class="right_col">
			Status: -
		</div>
	<% end%>
  <br /><br />
</div>
<br /><br />

<div class="form-actions">
	<%= link_to t('.Send_Application'),
                submit_application_path(@cs_application.id), :class => 'btn btn-primary', :confirm =>  'You will not be able to edit your application after it is submitted. Continue?' %>
	
    <%= link_to t('.print_review'),
                review_application_path(format: "pdf", id: @cs_application.id), :target => '_blank', :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cs_applications_path, :class => 'btn btn-warning' %>
</div>
	

app/views/cs_applications/show.html.erb
<%- model_class = CsApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @cs_application.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @cs_application.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:middle_name) %>:</strong></dt>
  <dd><%= @cs_application.middle_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @cs_application.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:towson_id_number) %>:</strong></dt>
  <dd><%= @cs_application.towson_id_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @cs_application.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cs_applications_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cs_application_path(@cs_application), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cs_application_path(@cs_application),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>